# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: classify.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'classify.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63lassify.proto\x12\x08\x63lassify\"+\n\x0cImageRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x0c\n\x04topk\x18\x02 \x01(\x05\")\n\nPrediction\x12\r\n\x05label\x18\x01 \x01(\t\x12\x0c\n\x04prob\x18\x02 \x01(\x02\"8\n\x12PredictionResponse\x12\"\n\x04topk\x18\x01 \x03(\x0b\x32\x14.classify.Prediction2O\n\nClassifier\x12\x41\n\x07Predict\x12\x16.classify.ImageRequest\x1a\x1c.classify.PredictionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'classify_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=28
  _globals['_IMAGEREQUEST']._serialized_end=71
  _globals['_PREDICTION']._serialized_start=73
  _globals['_PREDICTION']._serialized_end=114
  _globals['_PREDICTIONRESPONSE']._serialized_start=116
  _globals['_PREDICTIONRESPONSE']._serialized_end=172
  _globals['_CLASSIFIER']._serialized_start=174
  _globals['_CLASSIFIER']._serialized_end=253
# @@protoc_insertion_point(module_scope)
